# Generated by Django 3.1.5 on 2021-01-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=100)),
                ('field', models.ManyToManyField(to='employers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('job_type', models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=20)),
                ('listed_on', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('slots', models.FloatField(default=1)),
                ('support_contact', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer')),
            ],
        ),
    ]
